# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.listener.constructor_listener:
        class: AppBundle\EventListener\ConstructorListener
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    facebook.manager:
        class: AppBundle\Model\FacebookManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    geo_user.manager:
        class: AppBundle\Model\GeoUserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.object_manager", %fos_user.model.user.class%]

    api.exception_listener:
        class: ApiBundle\v1\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.geo_user_voter:
        class: AppBundle\Security\GeoUserVoter
        tags:
            - { name: security.voter }
        public: false

    serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name:serializer.normalizer }

    serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name:serializer.encoder }

    serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ["@serializer.method"]
            - {json: "@serializer.encoder.json" }
