# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.listener.constructor_listener:
        class: AppBundle\EventListener\ConstructorListener
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    facebook.manager:
        class: AppBundle\Model\FacebookManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    fleet.manager:
        class: AppBundle\Model\FleetManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    company.manager:
        class: AppBundle\Model\CompanyManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    geo_user.manager:
        class: AppBundle\Model\GeoUserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.object_manager", %fos_user.model.user.class%]

    position.manager:
        class: AppBundle\Model\DriverPositionManager
        arguments: ["@doctrine.orm.entity_manager"]

    api.exception_listener:
        class: ApiBundle\v1\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.geo_user_voter:
        class: AppBundle\Security\GeoUserVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false

    app.fleet_voter:
        class: AppBundle\Security\FleetVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false

    app.company_voter:
        class: AppBundle\Security\CompanyVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false

    app.position_voter:
        class: AppBundle\Security\PositionVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false

    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@service_container", "@security.token_storage"]

    app.fos_oauth_authenticator:
        class: AppBundle\Security\FOSOAuthAuthenticator
        arguments: ["@service_container", "@fos_oauth_server.server"]

    serializer.method:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name:serializer.normalizer }

    serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        tags:
            - { name:serializer.encoder }

    serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - ["@serializer.method"]
            - {json: "@serializer.encoder.json" }

