# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.listener.constructor_listener:
        class: AppBundle\EventListener\ConstructorListener
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }


#<service id="your_app.listener.before_controller" class="App\CoreBundle\EventListener\BeforeControllerListener" scope="request">
#    <tag name="kernel.event_listener" event="kernel.controller" method="onKernelController"/>
#    <argument type="service" id="security.context"/>
#</service>